#FROM python:3.8-slim-buster
#
#WORKDIR /app
#
#COPY requirements.txt .
#RUN pip install -r requirements.txt
#
#COPY . /app
#
#EXPOSE 8000
#
#CMD ["uvicorn", "app.main:app", "--host", "localhost"]
## CMD [ "python", "/app/main.py", "run" ]
